version: '3.8'
services:
  server:
    build: 
      context: ./server
      dockerfile: Dockerfile
    container_name: server
    env_file:
      - .env
    ports:
      - "8000:8000"
    restart: always
    
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: client
    depends_on:
      - server
    env_file:
      - .env
    ports:
      - "8501:8501"
    restart: always
networks:
  app:
    driver: bridge